var CONFIG = {

  SCREEN: {
    WIDTH: 640,
    HEIGHT: 360,
    LANDSCAPE: true,
    FPS: 60,
    BG_COLOR: '#000000'
  },

  TILE: {
    CELL_SIZE: 8,
    TILE_SIZE: 16,
    SCALE: 1.5,
    GRID_COLS: 44,
    GRID_ROWS: 26,
    BIG_TILE_COLS: 22,
    BIG_TILE_ROWS: 13,
    MAP_WIDTH: 352,
    MAP_HEIGHT: 208,
    CELL_SIZE_SCALED: 12,
    TILE_SIZE_SCALED: 24,
    MAP_WIDTH_SCALED: 528,
    MAP_HEIGHT_SCALED: 312,
    MAP_OFFSET_X: 0,
    MAP_OFFSET_Y: 0,
    INFO_PANEL_WIDTH: 0,
    BORDER_WIDTH: 2
  },

  TANK: {
    SIZE: 16,
    SIZE_SCALED: 24,
    HALF_SIZE: 8,
    HALF_SIZE_SCALED: 12,

    PLAYER_SPEEDS: [90, 120, 150, 180],
    PLAYER_BULLET_SPEEDS: [240, 240, 300, 300],
    PLAYER_BULLET_COUNTS: [1, 1, 2, 2],
    PLAYER_FIRE_RATES: [15, 12, 8, 6],
    PLAYER_CAN_PIERCE_STEEL: [false, false, false, true],

    ENEMY_BASIC_SPEED: 30,
    ENEMY_FAST_SPEED: 90,
    ENEMY_POWER_SPEED: 30,
    ENEMY_ARMOR_SPEED: 30,

    ENEMY_BASIC_BULLET_SPEED: 120,
    ENEMY_FAST_BULLET_SPEED: 120,
    ENEMY_POWER_BULLET_SPEED: 240,
    ENEMY_ARMOR_BULLET_SPEED: 120,

    ENEMY_BASIC_BULLET_COUNT: 1,
    ENEMY_FAST_BULLET_COUNT: 1,
    ENEMY_POWER_BULLET_COUNT: 1,
    ENEMY_ARMOR_BULLET_COUNT: 1,

    ENEMY_BASIC_FIRE_RATE: 60,
    ENEMY_FAST_FIRE_RATE: 45,
    ENEMY_POWER_FIRE_RATE: 30,
    ENEMY_ARMOR_FIRE_RATE: 45,

    BULLET_SIZE: 4,
    BULLET_SIZE_SCALED: 6,
    SPAWN_FLASH_DURATION: 500,
    SPAWN_FLASH_INTERVAL: 80
  },

  DIRECTION: {
    UP: 0,
    RIGHT: 1,
    DOWN: 2,
    LEFT: 3,
    DX: [0, 1, 0, -1],
    DY: [-1, 0, 1, 0]
  },

  TILE_TYPE: {
    EMPTY: 0,
    BRICK: 1,
    STEEL: 2,
    FOREST: 3,
    WATER: 4,
    ICE: 5,
    EAGLE: 6,
    EAGLE_DEAD: 7
  },

  ENEMY_TYPE: {
    BASIC: {
      ID: 0,
      SPEED: 30,
      HP: 1,
      SCORE: 100,
      BULLET_SPEED: 120,
      BULLET_COUNT: 1,
      FIRE_RATE: 60,
      COLOR_KEY: 'gray'
    },
    FAST: {
      ID: 1,
      SPEED: 90,
      HP: 1,
      SCORE: 200,
      BULLET_SPEED: 120,
      BULLET_COUNT: 1,
      FIRE_RATE: 45,
      COLOR_KEY: 'gray'
    },
    POWER: {
      ID: 2,
      SPEED: 30,
      HP: 1,
      SCORE: 300,
      BULLET_SPEED: 240,
      BULLET_COUNT: 1,
      FIRE_RATE: 30,
      COLOR_KEY: 'green'
    },
    ARMOR: {
      ID: 3,
      SPEED: 30,
      HP: 4,
      SCORE: 400,
      BULLET_SPEED: 120,
      BULLET_COUNT: 1,
      FIRE_RATE: 45,
      COLOR_KEY: 'armor'
    }
  },

  POWERUP_TYPE: {
    CLOCK: {
      ID: 0,
      NAME: 'clock',
      DURATION: 5000,
      DESCRIPTION: 'freeze all enemies'
    },
    GRENADE: {
      ID: 1,
      NAME: 'grenade',
      DURATION: 0,
      DESCRIPTION: 'destroy all enemies on screen'
    },
    HELMET: {
      ID: 2,
      NAME: 'helmet',
      DURATION: 10000,
      DESCRIPTION: 'temporary invincibility'
    },
    SHOVEL: {
      ID: 3,
      NAME: 'shovel',
      DURATION: 10000,
      DESCRIPTION: 'fortify base with steel walls'
    },
    TANK: {
      ID: 4,
      NAME: 'tank',
      DURATION: 0,
      DESCRIPTION: 'extra life'
    },
    STAR: {
      ID: 5,
      NAME: 'star',
      DURATION: 0,
      DESCRIPTION: 'upgrade player tank'
    }
  },

  GAME: {
    PLAYER_INITIAL_LIVES: 3,
    MAX_ENEMIES_ON_SCREEN: 4,
    TOTAL_ENEMIES_PER_LEVEL: 20,
    SPAWN_PROTECTION_TIME: 3000,
    POWERUP_DURATION: 10000,
    SHIELD_DURATION: 10000,
    FREEZE_DURATION: 5000,
    BASE_STEEL_DURATION: 10000,
    PLAYER_RESPAWN_DELAY: 1000,
    GAME_OVER_DELAY: 3000,
    LEVEL_COMPLETE_DELAY: 3000,
    POWERUP_SPAWN_CHANCE: 0.15,
    POWERUP_SPAWN_ENEMY_COUNT: 8,
    ENEMY_SPAWN_INTERVAL: 3000,
    ENEMY_SPAWN_POINTS: [
      { x: 9, y: 0 },
      { x: 21, y: 0 },
      { x: 33, y: 0 }
    ],
    PLAYER1_SPAWN: { x: 17, y: 24 },
    PLAYER2_SPAWN: { x: 25, y: 24 },
    EAGLE_POSITION: { x: 21, y: 24 },
    MAX_PLAYER_STARS: 3,
    ARMOR_FLASH_DURATION: 100,
    STAGE_INTRO_DURATION: 2000,
    SCORE_DISPLAY_DURATION: 3000
  },

  COLOR: {
    BLACK: '#000000',
    WHITE: '#FCFCFC',

    BRICK_DARK: '#8B4513',
    BRICK_MID: '#B53C14',
    BRICK_LIGHT: '#D88000',
    BRICK_HIGHLIGHT: '#F0A050',

    STEEL_DARK: '#7C7C7C',
    STEEL_MID: '#BCBCBC',
    STEEL_LIGHT: '#FCFCFC',

    WATER_DARK: '#0038A8',
    WATER_MID: '#0058F8',
    WATER_LIGHT: '#3CBCFC',
    WATER_SHINE: '#6888FC',

    FOREST_DARK: '#005800',
    FOREST_MID: '#00A800',
    FOREST_LIGHT: '#58D854',

    ICE_MID: '#BCBCBC',
    ICE_LIGHT: '#FCFCFC',
    ICE_SHINE: '#FFFFFF',

    EAGLE_BODY: '#F8B800',
    EAGLE_WING: '#D88000',
    EAGLE_EYE: '#000000',
    EAGLE_DEAD_DARK: '#444444',
    EAGLE_DEAD_MID: '#666666',

    PLAYER1_BODY: '#F8B800',
    PLAYER1_TRACK: '#B53C14',
    PLAYER1_TURRET: '#F8D878',
    PLAYER1_HIGHLIGHT: '#FCFCFC',

    PLAYER2_BODY: '#00A800',
    PLAYER2_TRACK: '#005800',
    PLAYER2_TURRET: '#58D854',
    PLAYER2_HIGHLIGHT: '#FCFCFC',

    ENEMY_BASIC_BODY: '#BCBCBC',
    ENEMY_BASIC_TRACK: '#7C7C7C',
    ENEMY_BASIC_TURRET: '#FCFCFC',

    ENEMY_FAST_BODY: '#BCBCBC',
    ENEMY_FAST_TRACK: '#7C7C7C',
    ENEMY_FAST_TURRET: '#FCFCFC',
    ENEMY_FAST_ACCENT: '#F8B800',

    ENEMY_POWER_BODY: '#00A800',
    ENEMY_POWER_TRACK: '#005800',
    ENEMY_POWER_TURRET: '#58D854',

    ENEMY_ARMOR_BODY: '#BCBCBC',
    ENEMY_ARMOR_TRACK: '#7C7C7C',
    ENEMY_ARMOR_TURRET: '#FCFCFC',
    ENEMY_ARMOR_FLASH: '#FCFCBC',
    ENEMY_ARMOR_DAMAGE1: '#F8B800',
    ENEMY_ARMOR_DAMAGE2: '#D88000',
    ENEMY_ARMOR_DAMAGE3: '#B53C14',

    BULLET_COLOR: '#FCFCFC',
    BULLET_TRAIL: '#BCBCBC',

    EXPLOSION_CENTER: '#FCFCFC',
    EXPLOSION_MID: '#F8B800',
    EXPLOSION_OUTER: '#D88000',
    EXPLOSION_EDGE: '#B53C14',

    SHIELD_COLOR: '#BCBCBC',
    SHIELD_FLASH: '#FCFCFC',

    SPAWN_FLASH_COLOR: '#FCFCFC',

    POWERUP_BG: '#000000',
    POWERUP_BORDER: '#F8B800',
    POWERUP_SYMBOL: '#FCFCFC',
    POWERUP_CLOCK_COLOR: '#F8B800',
    POWERUP_GRENADE_COLOR: '#B53C14',
    POWERUP_HELMET_COLOR: '#BCBCBC',
    POWERUP_SHOVEL_COLOR: '#D88000',
    POWERUP_TANK_COLOR: '#00A800',
    POWERUP_STAR_COLOR: '#F8B800',

    HUD_TEXT: '#FCFCFC',
    HUD_ENEMY_ICON: '#BCBCBC',
    HUD_LIVES_ICON: '#00A800',
    HUD_FLAG_ICON: '#F8B800',

    BORDER_COLOR: '#7C7C7C',
    BORDER_HIGHLIGHT: '#BCBCBC',

    WATER_ANIMATION: ['#0038A8', '#0058F8', '#3CBCFC', '#6888FC']
  },

  INPUT: {
    JOYSTICK_RADIUS: 48,
    JOYSTICK_INNER_RADIUS: 20,
    JOYSTICK_DEAD_ZONE: 0.2,
    JOYSTICK_OPACITY: 0.35,
    JOYSTICK_ACTIVE_OPACITY: 0.55,
    JOYSTICK_POSITION: { x: 80, y: 280 },

    FIRE_BUTTON_RADIUS: 28,
    FIRE_BUTTON_OPACITY: 0.4,
    FIRE_BUTTON_ACTIVE_OPACITY: 0.65,
    FIRE_BUTTON_POSITION: { x: 560, y: 280 },

    AUTO_FIRE_THRESHOLD: 300,
    AUTO_FIRE_INTERVAL: 150,

    PAUSE_BUTTON_SIZE: 24,
    PAUSE_BUTTON_OPACITY: 0.5,
    PAUSE_BUTTON_POSITION: { x: 610, y: 10 },

    SWIPE_THRESHOLD: 10,
    TAP_THRESHOLD: 8,
    MULTI_TOUCH: true
  }
};

module.exports = CONFIG;
